---
plugin: opsmill.infrahub.inventory
api_endpoint: "http://infrahub-server:8000"
branch: main

timeout: 30
strict: false
hostnames:
  - name

nodes:
  DcimDevice:
    include:
      - name
      - location.name
      - role
      - device_type.name
      # - device_type.platform.ansible_network_os
      - mgmt_ip.address
      - pod.parent.name
      - status

compose:
  ansible_host: mgmt_ip.address | regex_replace('/.*$', '')
  infrahub_fabric_name: pod.parent.name
  device_type: device_type.name
  # platform: device_type.platform.ansible_network_os
  location: location.name
