---
plugin: opsmill.infrahub.inventory
api_endpoint: "http://infrahub-server:8000"
branch: "{{ lookup('env', 'INFRAHUB_BRANCH') | default('main', true) }}"

timeout: 30
strict: false

nodes:
  DcimDevice:
    include:
      - name
      - location.name
      - pod.parent.name
      - role
      - device_type.name
      # - device_type.platform.ansible_network_os
      - primary_address.address
      - status

compose:
  hostname: name
  ansible_host: primary_address.address | ansible.utils.ipaddr('address')
  device_type: device_type.name
  # platform: device_type.platform.ansible_network_os
  location: location.name
  fabric: pod.parent.name
